version: '3.9'

services:
  dglib-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app/frontend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_CORE_API_URL: http://localhost:3000
      NEXT_PUBLIC_CORE_API_TIMEOUT: 1000000