version: '3.9'

services:
  postgresdb:
    image: postgres:15
    restart: always
    container_name: digital-lib-db-pg
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: digital_lib_db_docker