version: '3.9'

include:
  - ../docker-compose-db.yml

services:
  dglib-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    volumes:
      - ./backend:/app/backend
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://prisma:prisma@postgresdb:5432/digital_lib_db_docker?schema=public&connect_timeout=300