version: '3.9'

services:
  postgresdb:
    image: postgres:15
    restart: always
    container_name: digital-lib-db-pg
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: digital_lib_db_docker

  nestapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://prisma:prisma@postgresdb:5432/digital_lib_db_docker?schema=public&connect_timeout=300