# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Install, Build, Test & Deploy Backend
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_BACKEND_PROJECT_ID }}
on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize
    branches:
      - main
    paths:
      - "server/**"
  workflow_dispatch:

jobs:
  # Label of the container job
  build_backend:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:18

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:15
        # Provide the password for postgres
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: digital_lib_db_docker
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install, Integration & e2e test, Build
        run: |
          cd server
          npm install
          npm run test:cicd
          npm run test:e2e:cicd
          npm run build --if-present
        env:
          NODE_ENV: "test"
          DATABASE_URL: "postgresql://prisma:prisma@postgres:5432/digital_lib_db_docker?schema=public&connect_timeout=300"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./server
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_DEPLOY_TOKEN }}

      - name: Deploy to Vercel
        working-directory: ./server
        run: vercel --prod --confirm --token ${{ secrets.VERCEL_DEPLOY_TOKEN }}

